// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkaoXas61_jl-fHezwGFnZ-ocKek53xbo',
    appId: '1:1047947684824:web:5e77eb68ec5b91e7b360ad',
    messagingSenderId: '1047947684824',
    projectId: 'iha-clinic-web',
    authDomain: 'iha-clinic-web.firebaseapp.com',
    storageBucket: 'iha-clinic-web.firebasestorage.app',
    measurementId: 'G-YXYEHY46J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5N2TlliX9MuTQ91qZR-2sUXedL5ydP8',
    appId: '1:1047947684824:android:67cc7e2991c67700b360ad',
    messagingSenderId: '1047947684824',
    projectId: 'iha-clinic-web',
    storageBucket: 'iha-clinic-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ffxr7h6foiAFyVk0GXrh-wIG2OOBPVQ',
    appId: '1:1047947684824:ios:8b4a8b3920e44524b360ad',
    messagingSenderId: '1047947684824',
    projectId: 'iha-clinic-web',
    storageBucket: 'iha-clinic-web.firebasestorage.app',
    iosBundleId: 'com.example.ihaClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ffxr7h6foiAFyVk0GXrh-wIG2OOBPVQ',
    appId: '1:1047947684824:ios:8b4a8b3920e44524b360ad',
    messagingSenderId: '1047947684824',
    projectId: 'iha-clinic-web',
    storageBucket: 'iha-clinic-web.firebasestorage.app',
    iosBundleId: 'com.example.ihaClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkaoXas61_jl-fHezwGFnZ-ocKek53xbo',
    appId: '1:1047947684824:web:6b2f4092ae02fb18b360ad',
    messagingSenderId: '1047947684824',
    projectId: 'iha-clinic-web',
    authDomain: 'iha-clinic-web.firebaseapp.com',
    storageBucket: 'iha-clinic-web.firebasestorage.app',
    measurementId: 'G-C1PH3K5NX2',
  );
}
